title: gavinjerman.net
author: gavinjerman
description: under construction...
url: https://gavinjerman.github.io
show_downloads: false
theme: jekyll-theme-cayman
plugins:
    - jekyll-feed
    - jekyll-redirect-from
twitter:
  username: gavinjerman
  card: summary
